### ISSUE TITLE
Working example?

### ISSUE THREAD

**Issue by alanweissman** [sambragg/tradestation-client#1]
Thanks for posting this repo. I realize it's auto-generated, but do you have a snippet that shows how to do auth and execute calls? I've been able to get it 'working' but the streaming data seems to return empty results.

**Comment by sambragg** [comment]
I didn't end up using this library at all, as it contains way more functionality than my project needs. I just made the code available to the community as it was fairly buried away in Tradestation's documentation.

However, if you want to post your app's code, I can take a look and help you come up with the solution.

**Comment by alanweissman** [comment]
Thanks Sam here's the example from readme with a few updates.. I get the token using one of the public TradeStation repos and paste it in here and the results I get are 
`
{
Close:undefined
DownTicks:undefined
DownVolume:undefined
High:undefined
...
}
`
`
var TradestationApi = require('tradestation-client');
var defaultClient = TradestationApi.ApiClient.instance;

// Configure OAuth2 access token for authorization: OAuth2-Auth-Code
var OAuth2AuthCode = defaultClient.authentications['OAuth2-Auth-Code'];
OAuth2AuthCode.accessToken = "<token filled>"

// Configure OAuth2 access token for authorization: OAuth2-Refresh-Token
var OAuth2RefreshToken = defaultClient.authentications['OAuth2-Refresh-Token'];
OAuth2RefreshToken.accessToken = "<token filled>"

var api = new TradestationApi.BrokerageApi()
var apiInstance = new TradestationApi.MarketdataApi();

var accessToken = "<token filled>"; // {String} A valid OAuth2 token used to authorize access to the resource
var userId = "<username>"; // {String} User ID for Accounts Lookup

var callback = function(error, data, response) {
  if (error) {  
    console.error(error);
  } else {
    console.log('API called successfully. Returned data: ' + data);
    console.log(data);
  }
};

var symbol = "MSFT"; // String | A Symbol Name
var interval = 60; // Number | Interval that each bar will consist of. **For Daily, Weekly, and Monthly units this value must be 1.**
var unit = "Minute"; // String | Unit of time for each bar interval.
var daysBack = 1; // Number | The number of bars to stream, going back from time 00:00:00 of the day specified in lastDate. Cannot exceed greater than 57600 if unit is Minute.
var opts = {}

apiInstance.streamBarchartsDaysBack(accessToken, symbol, interval, unit, daysBack, opts, callback);
`

**Comment by sambragg** [comment]
@alanweissman I see you commented and then deleted your comment later. Did you manage to fix the issue? I'm going to close this, feel free to reopen if needed.
